# Generated by Django 4.2.9 on 2024-03-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationtier",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="donationtier",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
