# Generated by Django 4.2.9 on 2024-03-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_alter_donationtier_options_donationtier_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationtier",
            name="lookup_key",
        ),
        migrations.AlterField(
            model_name="donationtier",
            name="recurrence",
            field=models.IntegerField(choices=[(0, "month"), (1, "year")]),
        ),
    ]
